default_context:
    full_name: "{{cookiecutter.full_name}}"
    email: "{{cookiecutter.email}}"
    project_name: "{{cookiecutter.project_name}}"
    project_slug: "{{cookiecutter.project_slug}}"
    project_short_description: "{{cookiecutter.project_short_description}}"